feat: Add chart
lablabs/keeper pull request #1
Opened 2024-06-19 10:42 UTC by Balsir

# Description

Add keeper chart

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

2024-07-08 06:50 UTC, jaygridley requested changes

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/Chart.yaml
> +description: Helm chart for capacity reservation and overprovisioning
```suggestion
description: Helm chart for a node capacity reservation and overprovisioning
```

2024-07-08 06:50 UTC, jaygridley commented on README.md
> +keeper Helm chart.
I would like to describe how the "tool" can be used and what issues it solves. Basically, the same description from the main README.md would be ok. Or remove the description.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/templates/deployment-overprovisioning.yaml
> +      containers:
I would like to add security context for the Pod with "strict" policy.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/templates/deployment-reservation.yaml
> +      containers:
I would like to add security context for the Pod with "strict" policy.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/templates/role-cronjob.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
As we are allowing to customize the image, some might need a different RBAC control. I would make this optional, but enabled by default.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/values.yaml
> +  map:
```suggestion
  map: {}
```

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/values.yaml
> +  map:
```suggestion
  map: {}
```

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/templates/cronjob-overprovisioning-up.yaml
> +            resources:
I would like to add security context for the Pod with "strict" policy.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/templates/cronjob-reservation-down.yaml
> +            resources:
I would like to add security context for the Pod with "strict" policy.

2024-07-08 06:50 UTC, jaygridley commented on charts/keeper/values.yaml
> +  priorityClassOverride: ""
We could move this under `priorityClass` and rename to `name` and use if either for builtin priority class or custom one provided externally.

2025-10-25 11:19 UTC, Balsir commented on charts/keeper/templates/role-cronjob.yaml
> +apiVersion: rbac.authorization.k8s.io/v1
Image is customizable to e.g. configure private registry, not to change the functionality.
The rbac rules are fit for purpose, I don't see a reason to have them overridable at this time.

2025-10-30 16:48 UTC, Balsir commented on charts/keeper/values.yaml
> +  priorityClassOverride: ""
Not ideal, when you set create=true and provide a priority class name, the chart takes over an existing priorityClass.

2025-11-04 14:55 UTC, jaygridley requested changes

2025-11-04 14:55 UTC, jaygridley commented on .github/workflows/cache-warmup.yaml
> +          github_token: "" # workaround for Bridgecrew's API IP-safelisting
We agreed to remove this line, right?

2025-11-04 14:55 UTC, jaygridley commented on charts/keeper/values.yaml
> +  priorityClassOverride: ""
That's ArgoCD feature IMHO https://argo-cd.readthedocs.io/en/latest/user-guide/sync-options/#fail-the-sync-if-a-shared-resource-is-found not Helm's. Helm would fail that resource already exists. It would be a misconfiguration if you pass a PriorityClass name that already exists. Besides that I think it is a common community pattern to have name under priorityClass a use it when creating of adopting existing resource, for example https://github.com/kubernetes/ingress-nginx/blob/c10cb9f1a514d0ffc248d52dda21b288793461cc/charts/ingress-nginx/values.yaml#L1048 https://github.com/prometheus-community/helm-charts/blob/fe336479d023ffa08590a5958b044bfa4754c162/charts/kube-prometheus-stack/values.yaml#L3018

2025-11-04 14:55 UTC, jaygridley commented on charts/keeper/values.yaml
> +  image: ghcr.io/lablabs/kubectl:latest
Can we use official image [registry.k8s.io](https://explore.ggcr.dev/?repo=registry.k8s.io)/kubectl instead?

2025-11-04 15:29 UTC, Balsir commented on charts/keeper/values.yaml
> +  image: ghcr.io/lablabs/kubectl:latest
haven't tested registry.k8s.io, I am using bash in the query. And since we have an image, why not use it? :) but we can try it out

Most community charts have the priorityClass as an input, we create it. I wanted to make it clear via the configuration that those are basically two separate resources. priorityClass manages the one the chart creates, priorityClassOverride is the one that is provided. But you are right, from a strictly Helm point of view, it should be secure.

2025-11-04 15:30 UTC, Balsir commented on .github/workflows/cache-warmup.yaml
> +          github_token: "" # workaround for Bridgecrew's API IP-safelisting
Yup, will do.

2025-11-04 20:44 UTC, Balsir commented on charts/keeper/values.yaml
> +  image: ghcr.io/lablabs/kubectl:latest
official image doesnt have latest tag, how will we keep it updated?

2025-11-05 08:28 UTC, jaygridley commented on charts/keeper/values.yaml
> +  image: ghcr.io/lablabs/kubectl:latest
> official image doesnt have latest tag, how will we keep it updated?

Renovate could be an option. Or we can just set it to the current latest version for now.

2025-11-06 10:59 UTC, jaygridley commented on charts/keeper/values.yaml
> +  priorityClassOverride: ""
We agreed to keep the current approach.

2025-11-06 10:59 UTC, jaygridley approved these changes
LGTM

2025-11-06 11:42 UTC, merged